version: "3"
services:
  pytorch:
    build: .
    container_name: pytorch
    restart: always
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 5000:5000
    environment:
      - tz=Asia/Hong_Kong
      - DISPLAY=${DISPLAY}
      - CUDA_VISIBLE_DEVICES=""
    command: sh -c "sleep infinity"
    network_mode: host
    command: python3 main.py --device cpu -C ${RTMP_URL}
    # command: python3 main.py --device cpu -C test/Child-Run-Swimming-Pool-Fall-Down-Jump-Gifs-Gif.gif